import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'



/* 
TODO: Implement a navbar that has posts, projects, github
SPEC: The navbar should be vertical but one phone should turn into a menu bar
      
*/

/* 
TODO: Load custom font 
TODO: Add to vercel
TODO: Google Analytics
TODO: Add an A record to defunsm.ml 
*/

const Home: NextPage = () => {
  return (
    
    <div className={styles.container}>
      <NavBar />

      <Head>
        <title>defunSM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={styles.main}>
        <h1 className={styles.title}>
          Salman <a href="https://nextjs.org">Hossain</a> // <span className="rainbow-text alias">defunSM</span>
        </h1>
        
        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
